### ISSUE TITLE
Upgrade README.md

### ISSUE THREAD

**Issue by ewallace** [riboviz/example-datasets#54]
To do:
* [x] Use a small simulated dataset and Brar 2012 as "START HERE" examples.
* [x] Describe that A-site map goes in annotation folders (fixing #30)
* [x] Describe naming convention for `config.yaml` files, discussed in #53 
* [x] Update metadata/provenance format section, related to closing [riboviz#166](/riboviz/riboviz/issues/166)
* [x] Remind that when adding a new example dataset, should also update the kingdom README.md

**Comment by ewallace** [comment]
Starting new branch `readme-54` for this.

**Comment by ewallace** [comment]
Made updates partially addressing these points in the branch. Hoping to close next dev meeting.
