### ISSUE TITLE
Make issue template, with checklist, to add a new dataset

### ISSUE THREAD

**Issue by ewallace** [riboviz/example-datasets#72]
It would speed up and clarify adding new datasets if we created an issue template with a checklist, for all the components and testing. Let's do that.

**Comment by 3mma-mack** [comment]
I've tried to make a list of the steps and components that I can remember doing for adding a new dataset. Hopefully this is useful! 


 **For new species**

create contaminants folder:
-  rRNA fasta file
- - downloaded from relevant genome database
-  provenance text

create annotation folder: 
- transcriptome gff3
- transcriptome fasta file
- - both made using create_files_for_riboviz.R from genome gff and fasta, downloaded from relevant database 
- - check with check_fasta_gff.py and potentially SnapGene


**For existing species**

Dataset:
- identify paper and dataset to add
- find adapter sequence, and any potential UMIs and barcodes 
- find samples to run and their accession number from Sequence Read Archive (SRA)

config file:
- add provenance section
- include parameters as listed in prep-riboviz-config.md
- Take special care with adapters, and UMI regular expression 
- check paths to contaminants and annotation folder, make sure they are correct 

test run:
- set up riboviz on computer or on eddie - following either install.md or run-on-eddie.md
- download samples for the dataset using the accession number for the sample 
- run on riboviz nextflow pipeline
- - If it fails, check adapters, UMIs and paths to contaminants and annotation folders first
- check output graphs. Looking for:
- - most reads being 28 and 32 nt in length
- - 3nt periodicity

**Comment by ewallace** [comment]
[Github help on configuring issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by 3mma-mack** [comment]
> [Github help on configuring issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

Looking at the link above, the first step requires us going into settings in the repository, which neither Sophie or I seem to have for example datasets. I'm assuming we don't have permission to do this for the example datasets repository if we are not admins, as we do have the settings buttons for our own private repositories.

**Comment by ewallace** [comment]
I think that the issue template is just a .md file (same format as the issues). So we could create the issue template and modify it in a post on this thread, then when it's ready someone with admin access can upload?

**Comment by 3mma-mack** [comment]
Sounds like a good idea! So far we've been working on a larger document [here](https://github.com/3mma-mack/Riboviz-honours/blob/main/add-new-dataset.md), which we were planning on using as supporting information to the issue ticket template, which would be a more condensed checklist.

It's still in progress, but this is what we have so far.

**Comment by ewallace** [comment]
That is exciting! Looking very good, let's make it in to a documentation file, `example-datasets/add-new-dataset.md`, in the root directory, in a branch, and start working to merge it in. Some comments and feedback below.

* Add summary text "A guide to adding a new dataset for riboviz processing to example-datasets. For full riboviz documentation, see..."
* Could we be more precise about genus/species/ etc? Add new genus or species extends to adding a new annotation for an existing organism (e.g. ORFeome vs transcriptome) or a new strain. So we should be careful and thorough about what words we use and check the whole document.
* I am inspired to give `create_files_for_riboviz.R` a try.
* The add-new-dataset.md guide is a bit confused between checklists and bullet points. For a doc file bullet points are more intuitive; for an issue template/ticket the checklists are useful because you can tick them off.
* The scientific paper section assumes that people will be running on published data. We want it to be easy for people to run these on their own unpublished data too, maybe we should say that too?

When we move this into the repo, let's request @mikej888's input on which documentation belongs in riboviz/example-datasets vs in riboviz/riboviz. It makes sense to keep general docs at riboviz/riboviz, and lightweight docs more focused on using this repo at riboviz/example-datasets.

**Comment by ewallace** [comment]
I have put in pull request #84 to close #54. That is complementary to this.

We will need to update the repo README to:

* refer to add-new-dataset.md
* mention an issue template, when it exists

**Comment by swinterbourne** [comment]
> That is exciting! Looking very good, let's make it in to a documentation file, `example-datasets/add-new-dataset.md`, in the root directory, in a branch, and start working to merge it in.

The `example-datasets/add-new-dataset.md` is available in the branch add-new-dataset-documentation-72 in example-datasets.

**Comment by 3mma-mack** [comment]
I have created a basic template with a checklist of key steps. The markdown file is in my riboviz-honours repository [here](https://github.com/3mma-mack/Riboviz-honours/blob/main/.github/ISSUE_TEMPLATE/add-new-example-dataset.md).

My problem with the issue template is that the checklist is contained in the first comment, which looks messy in my eyes, but I guess it will look fine once the issue has been created. This will allow people to change the checklist as they go. Another problem is it slightly changes the way issues are created. It creates an extra screen where users have to select either the template they want to use or click to create a blank issue, which feels a little unnecessary when there is only one template. That is just me being unfamiliar with issue templates though.

**Comment by ewallace** [comment]
That template and checklist is almost there. Where else would it be helpful we link to specific documentation for specific steps?

Can we expand the test run and look at results bits, maybe something like
* [ ] (optional) create downsampled data and fast test run on that
* [ ] test run on full dataset
* [ ] Check results for 3nt periodicity on coding regions, and start and stop profiles
* [ ] Troubleshoot as needed
* [ ] Update genus-level README.md and provenance section of config file

I'm ok with changing the way issues are created.

**Comment by 3mma-mack** [comment]
I've updated the issue template to include more links to documentation and to include the test and result points you suggested. I have also included a link to the add-new-dataset.md document that Sophie and I have been working on.

**Comment by 3mma-mack** [comment]
I have also created an issue ticket template for adding a new species, which can be found [here](https://github.com/3mma-mack/Riboviz-honours/blob/main/.github/ISSUE_TEMPLATE/add-new-species.md)

I'm not sure where to go from here in terms of actually adding both issue templates to example datasets, but I think they are pretty much good to go!
